version: "2.0"

volumes:
  flowablemt_pgdata:
    driver: local

services:
  #
  # docker exec -it pg psql -u postgres
  #

  postgres:
    container_name: flowablemt
    image: postgres:12
    restart: "no"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - flowablemt_pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      default:
        aliases:
          - flowablemt

